title: Template
author: TeachBooks
logo: figures/TUDelft_logo_rgb.png
copyright: Delft University of Technology, CC BY 4.0

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - colon_fence
    - amsmath
    - dollarmath
    - attrs_inline
    - deflist
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"

sphinx:
  config:
    html_show_copyright: true
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://github.com/RolfHut/Design-Engineering-voor-Fysici-Dictaat"
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
          thebe: true
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches

bibtex_bibfiles: 
  - references.bib

